### ISSUE TITLE
⚙️ Set Up a Team Workflow

### ISSUE THREAD

**Issue by gitaclue1** [chingu-voyages/v28-svelte-team-09#2]
**__Task Description__**
- [ ] Decide on the coding standards the team must follow.
- [ ] Define the characteristics of your repo including the number of branches, branch names, & the workflow everyone must follow.
- [ ] Agree on the format of commit messages, how Pull Requests will be reviewed, and GitHub branch protection rules.
- [ ] Decide on where you’ll deploy your app and the branch to be considered as ‘production’ you’ll be deploying from.
- [ ] Decide on what meetings you’ll need each week and to save time, schedule them as recurring meetings. You might want to look ahead to [Develop the App](https://docs.google.com/document/d/10erbB9vJbPfRXOad5hPkUv27iqlVGnj1etRu-9QtTjs/edit#heading=h.csvhpxknom3k) to learn more about the types of meetings you’ll need.

**__Technical Considerations__**
N/a

**__Additional Considerations__**
[Setup Your Team Workflow (Chingu Handbook)](https://docs.chingu.io/voyage/project/workflow)
[Javascript Style Guides](https://codeburst.io/5-javascript-style-guides-including-airbnb-github-google-88cbc6b2b7aa)
[Defining a Git Workflow (Chingu Handbook)](https://docs.chingu.io/techres/gitworkflow)
[Git Branches (Chingu Handbook)](https://docs.chingu.io/techres/gitbranches)
[Git Commits (Chingu Handbook)](https://docs.chingu.io/techres/gitcommits)
[Git Pull Requests (Chingu Handbook)](https://docs.chingu.io/techres/gitprs)
