### ISSUE TITLE
🤝 Meet your team & schedule Kickoff meeting

### ISSUE THREAD

**Issue by gitaclue1** [chingu-voyages/v28-svelte-team-09#7]
**__Task Description__**
- [ ] Meet your team by adding your introduction to the Team Channel
- [ ] Start getting to know one another
- [ ] Start discussing what projects you would like to create
- [ ] Watch the [Voyage Team Roles](https://youtu.be/f_TzehtBliE) video to learn about the different roles members of your team may have signed up to fill.
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/f_TzehtBliE)
- [ ] Watch the [How to Select a Voyage Project](https://youtu.be/5Xv0C5VAKZc) video
[![video link](https://img.youtube.com/vi/Hdn1V645Rwk/0.jpg)](https://youtu.be/5Xv0C5VAKZc)

**__Technical Considerations__**
N/a

**__Additional Considerations__**
The [Meet Your team](https://docs.google.com/document/d/10erbB9vJbPfRXOad5hPkUv27iqlVGnj1etRu-9QtTjs/edit#heading=h.v5trq7s6zxcp) section of the Voyage Guide contains the steps to follow

Use [When2Meet](https://when2meet.com) to identify days & times when everyone on the team is available to meet.
